logging:
  level:
    root: INFO
    com.example.bci: DEBUG

spring:
  jackson:
    default-property-inclusion: NON_NULL

pattern:
  signup-request:
    # Password must contain
    # one digit from 1 to 9
    # one lowercase letter
    # one uppercase letter
    # one special character
    # no space
    # 8-16 characters long
    # https://stackoverflow.com/a/72686232/3013786
    password: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*\W)(?!.* ).{8,16}$
