logging:
  level:
    root: INFO
    com.example.bci: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, validate, update)
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console.enabled: true

pattern:
  signup-request:
    # Password must contain
    # one digit from 1 to 9
    # one lowercase letter
    # one uppercase letter
    # one special character
    # no space
    # 8-16 characters long
    # https://stackoverflow.com/a/72686232/3013786
    password: ^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*\W)(?!.* ).{8,16}$
