drop table if exists testdb.PHONES CASCADE;
drop table if exists testdb.USERS CASCADE;

create table testdb.PHONES (
    ID bigint generated by default as identity,
    CITY_CODE varchar(5),
    COUNTRY_CODE varchar(5),
    NUMBER varchar(30),
    USERS_ID varchar(255),
    primary key (ID)
);

create table testdb.USERS (
   ID varchar(255) not null,
   CREATED timestamp,
   EMAIL varchar(80),
   IS_ACTIVE boolean default true,
   LAST_LOGIN timestamp,
   MODIFIED timestamp,
   USERNAME varchar(20),
   PASSWORD varchar(16),
   primary key (ID)
);

alter table testdb.PHONES
add constraint FK_USERS_USERS_ID foreign key (USERS_ID) references testdb.USERS;