drop table if exists testdb.PHONES CASCADE;
drop table if exists testdb.USERS CASCADE;

create table testdb.PHONES (
    ID bigint generated by default as identity,
    CITY_CODE varchar(255),
    COUNTRY_CODE varchar(255),
    NUMBER varchar(255),
    USERS_ID varchar(255),
    primary key (ID)
);

create table testdb.USERS (
   ID varchar(255) not null,
   CREATED timestamp,
   EMAIL varchar(255),
   IS_ACTIVE boolean default true,
   LAST_LOGIN timestamp,
   MODIFIED timestamp,
   NAME varchar(255),
   PASSWORD varchar(255),
   primary key (ID)
);

alter table testdb.PHONES
add constraint FK_USERS_USERS_ID foreign key (USERS_ID) references testdb.USERS;